apiVersion: v1
kind: Service
metadata:
  name: ai-engine-service
  namespace: ai-agent-system
  labels:
    app: ai-engine
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: ai-engine