apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine
  namespace: ai-agent-system
  labels:
    app: ai-engine
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-engine
  template:
    metadata:
      labels:
        app: ai-engine
        tier: backend
    spec:
      containers:
      - name: ai-engine
        image: ai-agent-system/ai-engine:latest
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: NVIDIA_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: nvidia-api-key
        - name: SAMBANOVA_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: sambanova-api-key
        - name: CEREBRAS_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: cerebras-api-key
        - name: REDIS_HOST
          value: redis-service
        - name: POSTGRES_HOST
          value: postgres-service
        - name: MONGODB_URI
          value: mongodb://mongodb-service:27017
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5